import { AppListItemModel } from '../interfaces/app-list-item.model';

export const appList: AppListItemModel[] = [
  {
    id: 0,
    name: 'Object factory',
    isHealthDev: true,
    isHealthProd: true,
    healthDev: 'obj-factory-v1-dev',
    healthProd: 'obj-factory-v1',
    linkDev: 'https://obj-factory-v1-dev.blueprints.solutions/api/docs',
    linkProd: 'https://obj-factory-v1.blueprints.solutions/api/docs',
  },
  {
    id: 1,
    name: 'Object factory typeorm',
    isHealthDev: true,
    isHealthProd: true,
    healthDev: 'obj-factory-v1-typeorm-dev',
    healthProd: 'obj-factory-v1-typeorm',
    linkDev: 'https://obj-factory-v1-typeorm-dev.blueprints.solutions/api/docs',
    linkProd: 'https://obj-factory-v1-typeorm.blueprints.solutions/api/docs',
  },
  {
    id: 2,
    name: 'Authn (v.1.0)',
    isHealthDev: true,
    isHealthProd: true,
    healthDev: 'obj-factory-v1-authn-dev',
    healthProd: 'obj-factory-v1-authn',
    linkDev: 'https://obj-factory-v1-authn-dev.blueprints.solutions/api/docs',
    linkProd: 'https://obj-factory-v1-authn.blueprints.solutions/api/docs',
  },
  {
    id: 3,
    name: 'Authn (v.2.0)',
    isHealthDev: true,
    isHealthProd: true,
    healthDev: 'obj-factory-v2-authn-dev',
    healthProd: 'obj-factory-v2-authn',
    linkDev: 'https://obj-factory-v2-authn-dev.blueprints.solutions/api/docs',
    linkProd: 'https://obj-factory-v2-authn.blueprints.solutions/api/docs',
  },
  {
    id: 4,
    name: 'Authn (v.3.0)',
    isHealthDev: true,
    isHealthProd: true,
    healthDev: 'obj-factory-v3-authn-dev',
    healthProd: 'obj-factory-v3-authn',
    linkDev: 'https://obj-factory-v3-authn-dev.blueprints.solutions/api/docs',
    linkProd: 'https://obj-factory-v3-authn.blueprints.solutions/api/docs',
  },
  {
    id: 5,
    name: 'File storage',
    isHealthDev: true,
    isHealthProd: true,
    healthDev: 'obj-factory-v1-file-storage-dev',
    healthProd: 'obj-factory-v1-file-storage',
    linkDev: 'https://obj-factory-v1-file-storage-dev.blueprints.solutions/api/docs',
    linkProd: 'https://obj-factory-v1-file-storage.blueprints.solutions/api/docs',
  },
  {
    id: 6,
    name: 'Multifile storage',
    isHealthDev: true,
    isHealthProd: true,
    healthDev: 'obj-factory-v1-multifile-storage-dev',
    healthProd: 'obj-factory-v1-multifile-storage',
    linkDev: 'https://obj-factory-v1-multifile-storage-dev.blueprints.solutions/api/docs',
    linkProd: 'https://obj-factory-v1-multifile-storage.blueprints.solutions/api/docs',
  },
  {
    id: 7,
    name: 'Object viewer api',
    isHealthDev: true,
    isHealthProd: true,
    healthDev: 'obj-viewer-api-dev',
    healthProd: 'obj-viewer-api',
    linkDev: 'https://obj-viewer-api-dev.blueprints.solutions/api/docs',
    linkProd: 'https://obj-viewer-api.blueprints.solutions/api/docs',
  },
  {
    id: 8,
    name: 'Object factory ui react',
    isHealthDev: false,
    isHealthProd: false,
    healthDev: 'none',
    healthProd: 'none',
    linkDev: 'https://obj-factory-ui-react-v1-dev.blueprints.solutions/',
    linkProd: 'https://obj-factory-ui-react-v1.blueprints.solutions/',
  },
  {
    id: 9,
    name: 'Object factory ui ng (v.2.0)',
    isHealthDev: false,
    isHealthProd: false,
    healthDev: 'none',
    healthProd: 'none',
    linkDev: 'https://obj-factory-ui-ng-v1-dev.blueprints.solutions/',
    linkProd: 'https://obj-factory-ui-ng-v1.blueprints.solutions/',
  },
  {
    id: 10,
    name: 'Object factory ui ng (v.3.0)',
    isHealthDev: false,
    isHealthProd: false,
    healthDev: 'none',
    healthProd: 'none',
    linkDev: 'https://obj-factory-ui-ng-v3-dev.blueprints.solutions/',
    linkProd: 'https://obj-factory-ui-ng-v3-dev.blueprints.solutions/',
  },
];
