const CONFIG = {
  COGNITO_REGION: process.env.REACT_APP_COGNITO_REGION,
  COGNITO_USER_POOL_ID: process.env.REACT_APP_COGNITO_USER_POOL_ID,
  COGNITO_USER_CLIENT_ID: process.env.REACT_APP_COGNITO_USER_CLIENT_ID,
  COGNITO_DOMAIN: process.env.REACT_APP_COGNITO_DOMAIN,
  COGNITO_SCOPE: process.env.REACT_APP_COGNITO_SCOPE,
  IDENTITY_POOL_ID: process.env.REACT_APP_IDENTITY_POOL_ID,
  OAUTH_REDIRECT_SIGN_IN: process.env.REACT_APP_OAUTH_REDIRECT_SIGN_IN,
  OAUTH_REDIRECT_SIGN_OUT: process.env.REACT_APP_OAUTH_REDIRECT_SIGN_OUT,
  OAUTH_RESPONSE_TYPE: process.env.REACT_APP_OAUTH_RESPONSE_TYPE,
};

export default CONFIG;
